// Roster + ratings from "qweezy players teams ratings and rankings.xlsx" (Men's Doubles, Spring 2026).
// individualRating = USTA/NTRP. doublesRating = house projection (defaults to the individual
// rating where the sheet left it blank). teamNumber / teamRank = the sheet's team # and proposed
// 1-30 ranking. Suhail Vaseem is a substitute (no team).
export type RosterEntry = {
  name: string;
  individualRating: number;
  doublesRating: number;
  teamNumber: number | null;
  teamRank: number | null;
};

export const ROSTER: RosterEntry[] = [
  { name: "Eric Brown", individualRating: 4.5, doublesRating: 4.8, teamNumber: 1, teamRank: 2 },
  { name: "Kyle Ozaki", individualRating: 4.5, doublesRating: 4.6, teamNumber: 1, teamRank: 2 },
  { name: "John Barton", individualRating: 4.5, doublesRating: 4.8, teamNumber: 2, teamRank: 1 },
  { name: "Keith Bray", individualRating: 4.5, doublesRating: 4.9, teamNumber: 2, teamRank: 1 },
  { name: "Eric Marquez", individualRating: 4.5, doublesRating: 4.4, teamNumber: 3, teamRank: 4 },
  { name: "Asad Sawani", individualRating: 4.0, doublesRating: 4.3, teamNumber: 3, teamRank: 4 },
  { name: "Michael Tarsha", individualRating: 4.5, doublesRating: 4.5, teamNumber: 4, teamRank: 6 },
  { name: "Michael Turner", individualRating: 4.0, doublesRating: 4.0, teamNumber: 4, teamRank: 6 },
  { name: "Tim Chapman", individualRating: 4.0, doublesRating: 4.0, teamNumber: 5, teamRank: 5 },
  { name: "Ricky Doyle", individualRating: 4.5, doublesRating: 4.5, teamNumber: 5, teamRank: 5 },
  { name: "Matthew Haralson", individualRating: 4.0, doublesRating: 4.3, teamNumber: 6, teamRank: 3 },
  { name: "Nik Pai", individualRating: 4.5, doublesRating: 4.4, teamNumber: 6, teamRank: 3 },
  { name: "Jonathan Lass", individualRating: 4.0, doublesRating: 4.0, teamNumber: 7, teamRank: 10 },
  { name: "Vikram Grover", individualRating: 4.0, doublesRating: 4.0, teamNumber: 7, teamRank: 10 },
  { name: "St.John Dunne", individualRating: 4.0, doublesRating: 4.0, teamNumber: 8, teamRank: 11 },
  { name: "Juan Gonzalez", individualRating: 4.0, doublesRating: 4.0, teamNumber: 8, teamRank: 11 },
  { name: "Eddie Lewis", individualRating: 4.0, doublesRating: 4.2, teamNumber: 9, teamRank: 7 },
  { name: "Todd Preheim", individualRating: 4.0, doublesRating: 4.3, teamNumber: 9, teamRank: 7 },
  { name: "Troy Madres", individualRating: 4.0, doublesRating: 4.1, teamNumber: 10, teamRank: 8 },
  { name: "Jeff Kalikstein", individualRating: 4.0, doublesRating: 4.3, teamNumber: 10, teamRank: 8 },
  { name: "Jeff Albrecht", individualRating: 4.0, doublesRating: 4.3, teamNumber: 11, teamRank: 9 },
  { name: "Omar Boulden", individualRating: 4.0, doublesRating: 4.0, teamNumber: 11, teamRank: 9 },
  { name: "Jose Rodriguez", individualRating: 4.0, doublesRating: 4.2, teamNumber: 12, teamRank: 12 },
  { name: "Bob Del Pietro", individualRating: 3.5, doublesRating: 3.7, teamNumber: 12, teamRank: 12 },
  { name: "Dave Muhich", individualRating: 3.5, doublesRating: 3.8, teamNumber: 13, teamRank: 13 },
  { name: "Garrett Sprowls", individualRating: 4.0, doublesRating: 4.1, teamNumber: 13, teamRank: 13 },
  { name: "Jay Morrison", individualRating: 4.0, doublesRating: 4.0, teamNumber: 14, teamRank: 14 },
  { name: "Eric Giesler", individualRating: 3.5, doublesRating: 3.8, teamNumber: 14, teamRank: 14 },
  { name: "Jeff Jumonville", individualRating: 4.0, doublesRating: 4.0, teamNumber: 15, teamRank: 18 },
  { name: "Will Crenshaw", individualRating: 3.5, doublesRating: 3.5, teamNumber: 15, teamRank: 18 },
  { name: "Tom Carstens", individualRating: 3.5, doublesRating: 3.5, teamNumber: 16, teamRank: 20 },
  { name: "John McManus", individualRating: 3.5, doublesRating: 3.8, teamNumber: 16, teamRank: 20 },
  { name: "Eric Sellars", individualRating: 3.5, doublesRating: 3.9, teamNumber: 17, teamRank: 15 },
  { name: "Ryan Crossland", individualRating: 3.5, doublesRating: 3.8, teamNumber: 17, teamRank: 15 },
  { name: "Jay Snodgrass", individualRating: 3.5, doublesRating: 3.5, teamNumber: 18, teamRank: 21 },
  { name: "Blair Duncan", individualRating: 3.5, doublesRating: 3.7, teamNumber: 18, teamRank: 21 },
  { name: "Eric Webber", individualRating: 3.5, doublesRating: 3.8, teamNumber: 19, teamRank: 17 },
  { name: "Thiru Lakshman", individualRating: 3.5, doublesRating: 3.8, teamNumber: 19, teamRank: 17 },
  { name: "Chris Moose", individualRating: 3.5, doublesRating: 3.8, teamNumber: 20, teamRank: 16 },
  { name: "Lee Smith", individualRating: 3.5, doublesRating: 3.9, teamNumber: 20, teamRank: 16 },
  { name: "Josh Kerr", individualRating: 3.5, doublesRating: 3.7, teamNumber: 21, teamRank: 19 },
  { name: "Ken Leonard", individualRating: 3.5, doublesRating: 3.7, teamNumber: 21, teamRank: 19 },
  { name: "Brent Turnipseed", individualRating: 3.5, doublesRating: 3.5, teamNumber: 22, teamRank: 22 },
  { name: "Chris Morris", individualRating: 3.5, doublesRating: 3.5, teamNumber: 22, teamRank: 22 },
  { name: "Trey Dolezal", individualRating: 3.5, doublesRating: 3.5, teamNumber: 23, teamRank: 23 },
  { name: "Brian Pratt", individualRating: 3.5, doublesRating: 3.5, teamNumber: 23, teamRank: 23 },
  { name: "Ken Womack", individualRating: 3.5, doublesRating: 3.5, teamNumber: 24, teamRank: 24 },
  { name: "Chris Stutzman", individualRating: 3.5, doublesRating: 3.5, teamNumber: 24, teamRank: 24 },
  { name: "Brian McNamara", individualRating: 3.5, doublesRating: 3.5, teamNumber: 25, teamRank: 25 },
  { name: "Giulio Pappal", individualRating: 3.5, doublesRating: 3.5, teamNumber: 25, teamRank: 25 },
  { name: "Andrew Gallo", individualRating: 3.5, doublesRating: 3.5, teamNumber: 26, teamRank: 26 },
  { name: "Robert Bastion", individualRating: 3.0, doublesRating: 3.0, teamNumber: 26, teamRank: 26 },
  { name: "Eagle Robinson", individualRating: 3.5, doublesRating: 3.5, teamNumber: 27, teamRank: 27 },
  { name: "Rickey Hall", individualRating: 3.0, doublesRating: 3.0, teamNumber: 27, teamRank: 27 },
  { name: "Bill Brennan", individualRating: 3.5, doublesRating: 3.5, teamNumber: 28, teamRank: 28 },
  { name: "Tanner Bond", individualRating: 3.0, doublesRating: 3.0, teamNumber: 28, teamRank: 28 },
  { name: "Brett Birkeland", individualRating: 3.0, doublesRating: 3.0, teamNumber: 29, teamRank: 29 },
  { name: "Mark McKenzie", individualRating: 3.0, doublesRating: 3.0, teamNumber: 29, teamRank: 29 },
  { name: "Todd Davis", individualRating: 3.0, doublesRating: 3.0, teamNumber: 30, teamRank: 30 },
  { name: "Ed Winn", individualRating: 3.0, doublesRating: 3.0, teamNumber: 30, teamRank: 30 },
  { name: "Suhail Vaseem", individualRating: 4.0, doublesRating: 4.3, teamNumber: null, teamRank: null },
];
